### ISSUE TITLE
配置太繁琐了

### ISSUE THREAD

**Issue by qiaoyhh** [animalize/Ting_Android#2]
您好，有没有简便的方法 能正常体验一下项目！

**Comment by animalize** [comment]
只做这一步就可以了：
`2.配置电脑端程序`
然后固定一下电脑端IP，在Android APP里设置IP就可以了。

这一步就不用了：
`3.分别配置服务器端、PC端`

**Comment by animalize** [comment]
这个项目用的是老版百度SDK，程序还可以用。
最新版的SDK把在线合成、离线合成分开了，老版是有网用有线、没网或网络不好用离线。

**Comment by qiaoyhh** [comment]
> 这个项目用的是老版百度SDK，程序还可以使用。
> 
> 最新版的SDK把在线合成、离线合成分开了，老版是有网时用在线合成，没网或网络不好时用离线合成。

现在是项目打开没有文本数据，完全看不到效果，哈哈哈

**Comment by animalize** [comment]
> 现在是项目打开没有文本数据，完全看不到效果，哈哈哈

下载`2.配置电脑端程序`里的`Ting.zip`，解压就可以用了，自带Python环境、相关包。
